# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AccessKeyManager < Formula
  desc "CLI for rotating AWS Access Keys"
  homepage "https://github.com/stuarthicks/access_key_manager"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stuarthicks/access_key_manager/releases/download/v0.0.3/access_key_manager_Darwin_x86_64.tar.gz"
      sha256 "551ffded81d1b7b444e161db819f13c0b7672d4a7fda0fca8a1b01aeacb7c8c2"

      def install
        bin.install "access_key_manager"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stuarthicks/access_key_manager/releases/download/v0.0.3/access_key_manager_Darwin_arm64.tar.gz"
      sha256 "a14fca2003ed04c9a3cb3a096bd8815af99ba53b7810b45c6d870c8d26eefb1d"

      def install
        bin.install "access_key_manager"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stuarthicks/access_key_manager/releases/download/v0.0.3/access_key_manager_Linux_x86_64.tar.gz"
        sha256 "074e475f8981c3fda592eac06eb3b06eb08a13b44c45dddf149552519ee40523"

        def install
          bin.install "access_key_manager"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stuarthicks/access_key_manager/releases/download/v0.0.3/access_key_manager_Linux_arm64.tar.gz"
        sha256 "78bdf41b9701dde5c64ede67813dad658b0369f01dbcd0395f7f025589239b4e"

        def install
          bin.install "access_key_manager"
        end
      end
    end
  end

  test do
    system "#{bin}/access_key_manager -h"
  end
end
