# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AccessKeyManager < Formula
  desc "CLI for rotating AWS Access Keys"
  homepage "https://github.com/stuarthicks/access_key_manager"
  version "0.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/stuarthicks/access_key_manager/releases/download/v0.0.1/access_key_manager_Darwin_x86_64.tar.gz"
      sha256 "b73ef4b7ba429cfdb00a7c2a7e4526265f9fa09649963bf149eddeafc1e27ce3"

      def install
        bin.install "access_key_manager"
      end
    end
    on_arm do
      url "https://github.com/stuarthicks/access_key_manager/releases/download/v0.0.1/access_key_manager_Darwin_arm64.tar.gz"
      sha256 "e1772a0f6f32de52fd4c43d6e8bdebbf88756dda008e240670d4cc403570e6db"

      def install
        bin.install "access_key_manager"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stuarthicks/access_key_manager/releases/download/v0.0.1/access_key_manager_Linux_x86_64.tar.gz"
        sha256 "9c94b12af79b11ea3624042a5a9f522208bfba4b2a6b8c4054221380bbe67b2d"

        def install
          bin.install "access_key_manager"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stuarthicks/access_key_manager/releases/download/v0.0.1/access_key_manager_Linux_arm64.tar.gz"
        sha256 "e5cbdd1feaa78590210ac2a44c4758281337f32d487e145d0be1a3c5befb353f"

        def install
          bin.install "access_key_manager"
        end
      end
    end
  end

  test do
    system "#{bin}/access_key_manager -h"
  end
end
