# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AccessKeyManager < Formula
  desc "CLI for rotating AWS Access Keys"
  homepage "https://github.com/stuarthicks/access_key_manager"
  version "0.0.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/stuarthicks/access_key_manager/releases/download/v0.0.2/access_key_manager_Darwin_x86_64.tar.gz"
      sha256 "0134794a1d3e4c4c5610a6459961fe8e79f8659b4a12b8cccba806052c033545"

      def install
        bin.install "access_key_manager"
      end
    end
    on_arm do
      url "https://github.com/stuarthicks/access_key_manager/releases/download/v0.0.2/access_key_manager_Darwin_arm64.tar.gz"
      sha256 "7e8f3010d3f76c61ef41faafae6e530a5aa37de23cfed71c0ea9f7c2a0025b2c"

      def install
        bin.install "access_key_manager"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stuarthicks/access_key_manager/releases/download/v0.0.2/access_key_manager_Linux_x86_64.tar.gz"
        sha256 "e1dc46aee1700127330d9a080626f6b65ac39480cd6e7bedbb3392ce30f75bf5"

        def install
          bin.install "access_key_manager"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stuarthicks/access_key_manager/releases/download/v0.0.2/access_key_manager_Linux_arm64.tar.gz"
        sha256 "d4a7632b4857e87b0976632cd25161903a6b790c0059cadbd86b2b5066b997fc"

        def install
          bin.install "access_key_manager"
        end
      end
    end
  end

  test do
    system "#{bin}/access_key_manager -h"
  end
end
