# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DdbPlease < Formula
  desc "Convenience CLI for AWS DynamoDB"
  homepage "https://github.com/stuarthicks/ddb-please"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stuarthicks/ddb-please/releases/download/v0.0.1/ddb-please_Darwin_x86_64.tar.gz"
      sha256 "c3a670df4dd027153595fa65d9452942a008d451c2c0b3cd38a11a79d1d24baa"

      def install
        bin.install "ddb-please"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stuarthicks/ddb-please/releases/download/v0.0.1/ddb-please_Darwin_arm64.tar.gz"
      sha256 "14bde234577bb87e082498d5fb3838d7ddc1b5692bd33fa39420dc9af15d44b0"

      def install
        bin.install "ddb-please"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stuarthicks/ddb-please/releases/download/v0.0.1/ddb-please_Linux_x86_64.tar.gz"
      sha256 "1047814c29af7211a074831a41efcedd835a8b46ba7cee7488fbd7f55b3124b9"
      def install
        bin.install "ddb-please"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stuarthicks/ddb-please/releases/download/v0.0.1/ddb-please_Linux_arm64.tar.gz"
      sha256 "7cb61d10850cb47cadb2063278bef5312acf7fb500a212bc75e130dd82d5bfa0"
      def install
        bin.install "ddb-please"
      end
    end
  end

  test do
    system "#{bin}/ddb-please -h"
  end
end
