# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mrd < Formula
  desc "Decodes the primordial soup of video DRM headers"
  homepage "https://github.com/stuarthicks/mrd"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stuarthicks/mrd/releases/download/v1.0.0/mrd_Darwin_x86_64.tar.gz"
      sha256 "9dcaa71102c87c7c3aa159a2990cd1e5c004a19de3257cfd9fd7f9cf55928fbe"

      def install
        bin.install "mrd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stuarthicks/mrd/releases/download/v1.0.0/mrd_Darwin_arm64.tar.gz"
      sha256 "2089c198a02b5090641c5d75cc4be33b35676c1e087ca415827f02da88e645de"

      def install
        bin.install "mrd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stuarthicks/mrd/releases/download/v1.0.0/mrd_Linux_x86_64.tar.gz"
        sha256 "f7b58314df958dcc24ed70211e7decdae4ede09f1a7302b6f7b54b83f8d50890"

        def install
          bin.install "mrd"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stuarthicks/mrd/releases/download/v1.0.0/mrd_Linux_arm64.tar.gz"
        sha256 "c397e6bfabbf8a51470ccc7bd3811acda01c441adf5f5d623aaaa61a3342160b"

        def install
          bin.install "mrd"
        end
      end
    end
  end

  test do
    system "#{bin}/mrd -h"
  end
end
