# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mrd < Formula
  desc "Decodes the primordial soup of video DRM headers"
  homepage "https://github.com/stuarthicks/mrd"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stuarthicks/mrd/releases/download/v1.2.0/mrd_Darwin_x86_64.tar.gz"
      sha256 "9a94df0ece8c931bf7a105fbc505531679d7c2df7118ea6e5c00d632504beae9"

      def install
        bin.install "mrd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stuarthicks/mrd/releases/download/v1.2.0/mrd_Darwin_arm64.tar.gz"
      sha256 "8e85d1a3a5cf7f56eb200f5c2d34c9e05c741dbe9773311b332c56f2f81253c3"

      def install
        bin.install "mrd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/stuarthicks/mrd/releases/download/v1.2.0/mrd_Linux_x86_64.tar.gz"
      sha256 "571eea2be6161386222b2db7ea14e9d8db94f9fb6e8a151d2ad05a119d6e8a23"
      def install
        bin.install "mrd"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/stuarthicks/mrd/releases/download/v1.2.0/mrd_Linux_arm64.tar.gz"
      sha256 "52ab3de2d0800d06dc349faeda9f3aa3c0a39f4fc6a953dc2a0eb77cedc93310"
      def install
        bin.install "mrd"
      end
    end
  end

  test do
    system "#{bin}/mrd -h"
  end
end
