# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oauth2Token < Formula
  desc "Convenience wrapper for getting oauth2 tokens to use with other tools, eg. curl."
  homepage "https://github.com/stuarthicks/oauth2_token"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/stuarthicks/oauth2_token/releases/download/v0.1.0/oauth2_token_Darwin_x86_64.tar.gz"
      sha256 "05ad5143abe53a30df66770a71f5aaefe1b2957330fbd955df76058b0e9c7ad0"

      def install
        bin.install "oauth2_token"
      end
    end
    on_arm do
      url "https://github.com/stuarthicks/oauth2_token/releases/download/v0.1.0/oauth2_token_Darwin_arm64.tar.gz"
      sha256 "bbbd395edd0effc82546b34c868d7c386c6ef59248b6d7ca052a71d1f874d56e"

      def install
        bin.install "oauth2_token"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stuarthicks/oauth2_token/releases/download/v0.1.0/oauth2_token_Linux_x86_64.tar.gz"
        sha256 "1cc862f2a776b2f4494f2aaceccc5858d131c5509519853477e9f4be792bcdf3"

        def install
          bin.install "oauth2_token"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stuarthicks/oauth2_token/releases/download/v0.1.0/oauth2_token_Linux_arm64.tar.gz"
        sha256 "9f8cef336fc1f7a14f6e95d3e212d90a44f28d89b078122a5410eaa694f0e5e1"

        def install
          bin.install "oauth2_token"
        end
      end
    end
  end

  test do
    system "#{bin}/oauth2_token -h"
  end
end
