# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oauth2Token < Formula
  desc "Convenience wrapper for getting oauth2 tokens to use with other tools, eg. curl."
  homepage "https://github.com/stuarthicks/oauth2_token"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/stuarthicks/oauth2_token/releases/download/v0.2.0/oauth2_token_Darwin_x86_64.tar.gz"
      sha256 "144f32c165bcb572f6d4e5386afb54040c1189ca0800e35c288892f1f663fc55"

      def install
        bin.install "oauth2_token"
      end
    end
    on_arm do
      url "https://github.com/stuarthicks/oauth2_token/releases/download/v0.2.0/oauth2_token_Darwin_arm64.tar.gz"
      sha256 "1a256cc19dd553d0c411e2e98ab5a379eb99d8d5ea1cf9a9b2eb98080f4a9651"

      def install
        bin.install "oauth2_token"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stuarthicks/oauth2_token/releases/download/v0.2.0/oauth2_token_Linux_x86_64.tar.gz"
        sha256 "7d68df93081a7c470003869a9c9e008e887c5acfdc445c38773ca47899c289cf"

        def install
          bin.install "oauth2_token"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stuarthicks/oauth2_token/releases/download/v0.2.0/oauth2_token_Linux_arm64.tar.gz"
        sha256 "fd9148e6ffaaa6288e8bfef7adbab1a47537955ae1191ee15e56e4038c52a660"

        def install
          bin.install "oauth2_token"
        end
      end
    end
  end

  test do
    system "#{bin}/oauth2_token -h"
  end
end
