# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oauth2Token < Formula
  desc "Convenience wrapper for getting oauth2 tokens to use with other tools, eg. curl."
  homepage "https://github.com/stuarthicks/oauth2_token"
  version "0.0.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/stuarthicks/oauth2_token/releases/download/v0.0.2/oauth2_token_Darwin_x86_64.tar.gz"
      sha256 "15fcaf518e8ef4edb5ae517ea9ee7fedaa3234b165d8f519d2a8020103dee6b7"

      def install
        bin.install "oauth2_token"
      end
    end
    on_arm do
      url "https://github.com/stuarthicks/oauth2_token/releases/download/v0.0.2/oauth2_token_Darwin_arm64.tar.gz"
      sha256 "63d3fdcb76cb36161fabaa4c16767a976922f0c0538a1ea8fba6e12aa31a79f8"

      def install
        bin.install "oauth2_token"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stuarthicks/oauth2_token/releases/download/v0.0.2/oauth2_token_Linux_x86_64.tar.gz"
        sha256 "5ecfd9d96b863ccd3160f8f847ddfef94d4616c867e73c84b528f0ee779a772c"

        def install
          bin.install "oauth2_token"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stuarthicks/oauth2_token/releases/download/v0.0.2/oauth2_token_Linux_arm64.tar.gz"
        sha256 "3ad86f070667b92516392fa99cad6727348cef99a3e3e2337e5520bfc9c1035b"

        def install
          bin.install "oauth2_token"
        end
      end
    end
  end

  test do
    system "#{bin}/oauth2_token -h"
  end
end
