# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rextract < Formula
  desc "Simple shell regex capture extractor"
  homepage "https://github.com/stuarthicks/rextract"
  version "0.0.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/stuarthicks/rextract/releases/download/v0.0.2/rextract_Darwin_x86_64.tar.gz"
      sha256 "a574497d1e4b8febe390a0643cdacc6ec8c4d40c0f54ffc308a26535514dbc88"

      def install
        bin.install "rextract"
      end
    end
    on_arm do
      url "https://github.com/stuarthicks/rextract/releases/download/v0.0.2/rextract_Darwin_arm64.tar.gz"
      sha256 "185bbffe0c8cf2bc73e595fa0208fa5263509296e9af052f89d0df83bbf312b8"

      def install
        bin.install "rextract"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stuarthicks/rextract/releases/download/v0.0.2/rextract_Linux_x86_64.tar.gz"
        sha256 "ba49417c0c7988b15b90ae7e81f82d6537690286f657d3a4a988c6f89e018b34"

        def install
          bin.install "rextract"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stuarthicks/rextract/releases/download/v0.0.2/rextract_Linux_arm64.tar.gz"
        sha256 "7e894f80e67456ed08f65a1902a88ab896f56e9d28aab1ecf7e9410b2a235888"

        def install
          bin.install "rextract"
        end
      end
    end
  end

  test do
    system "#{bin}/rextract -h
  end
end
