# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rextract < Formula
  desc "Simple shell regex capture extractor"
  homepage "https://github.com/stuarthicks/rextract"
  version "0.0.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/stuarthicks/rextract/releases/download/v0.0.3/rextract_Darwin_x86_64.tar.gz"
      sha256 "fbf6fe462bd568033ab7bde00941e4b0472a403defac9d92889100a1122c81bb"

      def install
        bin.install "rextract"
      end
    end
    on_arm do
      url "https://github.com/stuarthicks/rextract/releases/download/v0.0.3/rextract_Darwin_arm64.tar.gz"
      sha256 "92c7898ffcbd2065add6485e07787a7e4b1170df001ae3c72e98db15a43a8c8e"

      def install
        bin.install "rextract"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stuarthicks/rextract/releases/download/v0.0.3/rextract_Linux_x86_64.tar.gz"
        sha256 "139d03b018208b9d9cd068bf8326420e3dcc7585f96b50bf78b3fd13d9eef632"

        def install
          bin.install "rextract"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stuarthicks/rextract/releases/download/v0.0.3/rextract_Linux_arm64.tar.gz"
        sha256 "93da77c3517c181a0da8d33220293f87051d4980b2a165487b59251abe7029f1"

        def install
          bin.install "rextract"
        end
      end
    end
  end

  test do
    system "#{bin}/rextract -h"
  end
end
