# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tid < Formula
  desc "Barebones TypeID CLI generator"
  homepage "https://github.com/stuarthicks/tid"
  version "0.0.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/stuarthicks/tid/releases/download/v0.0.2/tid_Darwin_x86_64.tar.gz"
      sha256 "95713553f3c697cbd3e320c73601efaa40ffdbbe9b86fbbf2c88255110fe4d7b"

      def install
        bin.install "tid"
      end
    end
    on_arm do
      url "https://github.com/stuarthicks/tid/releases/download/v0.0.2/tid_Darwin_arm64.tar.gz"
      sha256 "a74237024b48fd5dd24589d204a910d8a14960025cacf5fe0470de1ddda6303b"

      def install
        bin.install "tid"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stuarthicks/tid/releases/download/v0.0.2/tid_Linux_x86_64.tar.gz"
        sha256 "291bcf00aa3ba36153119198fd5abde11cf9df0078f33eb520ee3efd9762ca3e"

        def install
          bin.install "tid"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stuarthicks/tid/releases/download/v0.0.2/tid_Linux_arm64.tar.gz"
        sha256 "b09658bf32d7ae223b4bba0508ddbc0f0b14562f6a3c86ee81d985d224e27e1d"

        def install
          bin.install "tid"
        end
      end
    end
  end

  test do
    system "#{bin}/tid -h"
  end
end
