# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tid < Formula
  desc "Barebones TypeID CLI generator"
  homepage "https://github.com/stuarthicks/tid"
  version "0.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/stuarthicks/tid/releases/download/v0.0.1/tid_Darwin_x86_64.tar.gz"
      sha256 "e2a437e77b8a3e78ce8ee70d4e8d7e788d61de0a4a9bc86dd65494c508380660"

      def install
        bin.install "tid"
      end
    end
    on_arm do
      url "https://github.com/stuarthicks/tid/releases/download/v0.0.1/tid_Darwin_arm64.tar.gz"
      sha256 "111efce7927e9895d9d65ba225f1a710e9227ad032e8bd7835b38be9cf7002b3"

      def install
        bin.install "tid"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stuarthicks/tid/releases/download/v0.0.1/tid_Linux_x86_64.tar.gz"
        sha256 "af7a7ef0676806fecfd12e4bc3d71339eabb87869babc8ce2af9c19dc7ee5d6c"

        def install
          bin.install "tid"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stuarthicks/tid/releases/download/v0.0.1/tid_Linux_arm64.tar.gz"
        sha256 "ae0d3feae4ccdb3a8e2619b35c45d37979b7bca571301483603d4d771b8a3c50"

        def install
          bin.install "tid"
        end
      end
    end
  end

  test do
    system "#{bin}/tid -h"
  end
end
