# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tid < Formula
  desc "Convenience wrapper for getting oauth2 tokens to use with other tools, eg. curl."
  homepage "https://github.com/stuarthicks/oauth2_token"
  version "0.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/stuarthicks/oauth2_token/releases/download/v0.0.1/oauth2_token_Darwin_x86_64.tar.gz"
      sha256 "fef6a9c9ebfeb6b98fb1522926ab7a16e0c8bac73fee1f9564d947db01181935"

      def install
        bin.install "oauth2_token"
      end
    end
    on_arm do
      url "https://github.com/stuarthicks/oauth2_token/releases/download/v0.0.1/oauth2_token_Darwin_arm64.tar.gz"
      sha256 "0ba0e04c31b53c629c80d1066fef835d597c5c9f22614996dcc132de1f668a90"

      def install
        bin.install "oauth2_token"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stuarthicks/oauth2_token/releases/download/v0.0.1/oauth2_token_Linux_x86_64.tar.gz"
        sha256 "326a2b2f05cecaded157167d0ce9f135c905049f2b240cd46b24f8f5c21cb791"

        def install
          bin.install "oauth2_token"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stuarthicks/oauth2_token/releases/download/v0.0.1/oauth2_token_Linux_arm64.tar.gz"
        sha256 "35d8b0ff364e7d2b6f589ec47d2278da053b0e2d670d8eb2fdab29ec577c8088"

        def install
          bin.install "oauth2_token"
        end
      end
    end
  end

  test do
    system "#{bin}/oauth2_token -h"
  end
end
