# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TlsCertInfo < Formula
  desc "CLI for viewing basic TLS (SSL) Certificate information"
  homepage "https://github.com/stuarthicks/tls_cert_info"
  version "0.0.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/stuarthicks/tls_cert_info/releases/download/v0.0.2/tls_cert_info_Darwin_x86_64.tar.gz"
      sha256 "0aa26e4ec9c98fb6949a44302c64b7d9fcf6f45fdce24b73cfaf144037d116ff"

      def install
        bin.install "tls_cert_info"
      end
    end
    on_arm do
      url "https://github.com/stuarthicks/tls_cert_info/releases/download/v0.0.2/tls_cert_info_Darwin_arm64.tar.gz"
      sha256 "8846faedd0bcdeae951629f66a7818664832989250f90197e9c3b047d0c60837"

      def install
        bin.install "tls_cert_info"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stuarthicks/tls_cert_info/releases/download/v0.0.2/tls_cert_info_Linux_x86_64.tar.gz"
        sha256 "216186606519b92bf73eaf5d4fd3405070cd5f8fc3c1e43b48478de21e494c0a"

        def install
          bin.install "tls_cert_info"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stuarthicks/tls_cert_info/releases/download/v0.0.2/tls_cert_info_Linux_arm64.tar.gz"
        sha256 "690e9b139ea62e3ee8d757e15222567dcc7c6dbd463ae976bf9f4a308f5a8057"

        def install
          bin.install "tls_cert_info"
        end
      end
    end
  end

  test do
    system "#{bin}/tls_cert_info -h"
  end
end
