# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TlsCertInfo < Formula
  desc "CLI for viewing basic TLS (SSL) Certificate information"
  homepage "https://github.com/stuarthicks/tls_cert_info"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stuarthicks/tls_cert_info/releases/download/v0.3.0/tls_cert_info_Darwin_x86_64.tar.gz"
      sha256 "ca027e41fb634a031cbfb627e7a59c28025d0eabd13a1aae8a7f7cdd0c3cd70d"

      def install
        bin.install "tls_cert_info"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stuarthicks/tls_cert_info/releases/download/v0.3.0/tls_cert_info_Darwin_arm64.tar.gz"
      sha256 "f16f1a0ba16d58c715091646f42d74f9d56e10fa6e01a96782b567f8bd356afe"

      def install
        bin.install "tls_cert_info"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stuarthicks/tls_cert_info/releases/download/v0.3.0/tls_cert_info_Linux_x86_64.tar.gz"
        sha256 "677a7adc25f330328c15cdc98133154ed181e2209785dbc5f08873adec86900c"

        def install
          bin.install "tls_cert_info"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/stuarthicks/tls_cert_info/releases/download/v0.3.0/tls_cert_info_Linux_arm64.tar.gz"
        sha256 "585e0d84c71f9c45a5d7916f202eb42de30ee87348a3d4c6d47e769f1593d117"

        def install
          bin.install "tls_cert_info"
        end
      end
    end
  end

  test do
    system "#{bin}/tls_cert_info -h"
  end
end
